language: ruby
dist: xenial
sudo: false
cache: bundler
rvm:
  - 2.6.2
addons:
  apt:
    packages:
      - vim-gtk
env:
  - TRAVIS_CI=1
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "vim --version"
